spring:
  profiles: default

eureka:
  client:
    healthcheck:
      enabled: true

zuul:
  debug:
    request: true

  routes:
    employee:
      path: /employee/**
      url: http://empms-employee:8083/employee
      service-id: /employee/**

    attendance:
      path: /attendance/**
      url: http://empms-attendance:8081/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://empms-salary:8082/salary
      service-id: /salary/**
